# 欢迎来到 Jekyll！
#
# 这个配置文件用于存放影响您整个站点的设置，
# 这些值通常您只需设置一次，之后很少需要编辑。
# 由于技术原因，当您使用 `jekyll serve -l -H localhost` 命令时，此文件*不会*自动重新加载。
# 如果您更改了此文件，请重新启动服务进程。

# 网站基础设置
locale                   : "zn-CN"
site_theme               : "default"
title                    : "HaoNan's Academic Home"
title_separator          : "-"
name                     : &name "HaoNan Tang"
description              : &description "Bachelor's student in Artificial Intelligence at Wuhan University of Technology (2022–2026)"
url                      : https://codelancera-offical.github.io # 网站的基础主机名和协议，例如 "https://[你的GitHub用户名].github.io"；如果你已经在Github上托管了其他页面，则使用 "https://[你的GitHub用户名].github.io/[你的仓库名]"
baseurl                  : "" # 网站的子路径，例如 "/blog"
repository               : "codelancera-offical/codelancera-offical.github.io"

# 网站作者 - 以下设置控制侧边栏作者信息部分显示的内容。
#               如果某个字段为空，对应的图标和链接将不会显示，否则将会显示。
#               更多的自定义可以通过编辑 `/_includes/author-profile.html` 文件来实现。
author:
  # 个人简介信息
  avatar                 : "me.jpg"
  name                   : "HaoNan Tang"
  bio                    : "AI undergraduate in WUT."
  location               : "Wuhan, China"
  employer               : "Wuhan University of Technology"
  email                  : "lancera.thn@gmail.com"

  # 学术网站
  arxiv                  : # 网址 - 请更新为您正确的个人主页链接
  googlescholar          :

  # 代码仓库和软件开发
  github                 : "https://github.com/codelancera-offical"

  # 社交媒体
  youtube                : # 用户名
  zhihu                  : # 用户名

# 出版物分类 - 以下是出版物分类及其标题的列表
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# 网站设置
teaser                   :  # 摘要的备用图片文件名，图片放在 /images/ 目录下，例如 "500x300.png"
breadcrumbs              : false # 是否显示面包屑导航，可选：true, false (默认)
words_per_minute         : 160
future                   : true # 是否显示发布日期在未来的文章
read_more                : "disabled" # 如果启用，将在文章摘要后添加“阅读更多”链接
talkmap_link             : false      # 改为 true 可在演讲页面上添加 talkmap 的链接
comments:
  provider               : # 评论系统提供商，可选：false (默认), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # 例如：meta.discourse.org，参考 https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963
  facebook:
    appid                :
    num_posts            : # 显示的评论数，5 (默认)
    colorscheme          : # 配色方案, "light" (默认), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # 分支名，例如 "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # 日期格式: "iso8601" (默认), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false # 改为 true 可在页脚隐藏 RSS 订阅链接
  path                   : # 留空 (默认) 使用 feed.xml


# SEO 相关设置
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# 社交分享
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # 社交媒体分享时默认显示的网站图片
og_description           :  # 社交媒体分享时默认显示的网站描述
# 用于指定社交媒体个人资料
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # 类型：Person (个人) 或 Organization (组织) (默认为 Person)
  name                   : # 如果用户或组织的名称与站点名称不同
  links: # 一个包含社交媒体个人资料链接的数组


# 网站分析
analytics:
  provider               :  "false" # 分析工具提供商，可选：false (默认), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# 文件读取
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# 格式转换
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# 这些设置控制模板使用的“集合（collections）”类型
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# 这些设置控制页面和集合如何被包含在站点中
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # 输出样式，可选：expanded, compressed (http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style)


# 输出设置
permalink: /:categories/:title/
# paginate: 5 # 每页显示的帖子数量
# paginate_path: /page:num/
timezone: Etc/UTC # 时区，请参考 tz 数据库时区列表 (http://en.wikipedia.org/wiki/List_of_tz_database_time_zones)


# 插件
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# 使用 --safe 选项模拟 GitHub Pages 环境时，只加载白名单中的插件
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# 归档页面
#  类型 (Type)
#  - 使用 Liquid 构建的与 GitHub Pages 兼容的归档页面 ~> type: liquid (默认)
#  - 使用 jekyll-archives 插件构建的归档页面 ~> type: jekyll-archives
#  路径 (Path) (示例)
#  - 使用 Liquid 方法时，归档页面应存在于指定路径，否则可能导致链接损坏（尤其是在启用面包屑导航时）
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML 压缩
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development